version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
