/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionModelTagAllOf } from './collectionModelTagAllOf';
import { CollectionModel } from './collectionModel';
import { Pageable } from './pageable';
import { PageablePage } from './pageablePage';
import { CollectionModelLinks } from './collectionModelLinks';
import { CollectionModelTagAllOfEmbedded } from './collectionModelTagAllOfEmbedded';

export interface CollectionModelTag extends CollectionModel, Pageable {
  _embedded?: CollectionModelTagAllOfEmbedded;
}
