/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudyCourse } from './studyCourse';
import { Links } from './links';
import { Link } from './link';

export interface EntityModelStudyCourse extends Links {
  referencedEntity?: string;
  name?: string;
  academicDegree?: EntityModelStudyCourse.AcademicDegreeEnum;
}
export namespace EntityModelStudyCourse {
  export type AcademicDegreeEnum = 'BACHELOR' | 'MASTER' | 'UNKNOWN';
  export const AcademicDegreeEnum = {
    Bachelor: 'BACHELOR' as AcademicDegreeEnum,
    Master: 'MASTER' as AcademicDegreeEnum,
    Unknown: 'UNKNOWN' as AcademicDegreeEnum
  };
}
