/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Links } from './links';
import { ProjectStudyCourse } from './projectStudyCourse';
import { Link } from './link';

export interface EntityModelProjectStudyCourse extends Links {
  academicDegree?: EntityModelProjectStudyCourse.AcademicDegreeEnum;
  readonly id?: string;
  name?: string;
}
export namespace EntityModelProjectStudyCourse {
  export type AcademicDegreeEnum = 'BACHELOR' | 'MASTER';
  export const AcademicDegreeEnum = {
    Bachelor: 'BACHELOR' as AcademicDegreeEnum,
    Master: 'MASTER' as AcademicDegreeEnum
  };
}
