/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Links } from './links';
import { Link } from './link';

export interface EntityModelProject extends Links {
  created?: string;
  readonly creatorID: string;
  readonly creatorName: string;
  description: string;
  readonly id?: string;
  modified?: string;
  name: string;
  requirement?: string;
  shortDescription: string;
  status?: EntityModelProject.StatusEnum;
  supervisorName: string;
}
export namespace EntityModelProject {
  export type StatusEnum = 'ABGESCHLOSSEN' | 'VERFÜGBAR' | 'LAUFEND';
  export const StatusEnum = {
    Abgeschlossen: 'ABGESCHLOSSEN' as StatusEnum,
    Verfgbar: 'VERFÜGBAR' as StatusEnum,
    Laufend: 'LAUFEND' as StatusEnum
  };
}
