/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectModule } from './projectModule';
import { Links } from './links';
import { Link } from './link';

export interface EntityModelProjectModule extends Links {
  readonly id?: string;
  name?: string;
  projectType?: EntityModelProjectModule.ProjectTypeEnum;
}
export namespace EntityModelProjectModule {
  export type ProjectTypeEnum = 'BA' | 'MA' | 'PP' | 'UNDEFINED';
  export const ProjectTypeEnum = {
    Ba: 'BA' as ProjectTypeEnum,
    Ma: 'MA' as ProjectTypeEnum,
    Pp: 'PP' as ProjectTypeEnum,
    Undefined: 'UNDEFINED' as ProjectTypeEnum
  };
}
