/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Module {
  id?: string;
  name?: string;
  description?: string;
  projectType?: Module.ProjectTypeEnum;
}
export namespace Module {
  export type ProjectTypeEnum = 'UNDEFINED' | 'PP' | 'BA' | 'MA';
  export const ProjectTypeEnum = {
    Undefined: 'UNDEFINED' as ProjectTypeEnum,
    Pp: 'PP' as ProjectTypeEnum,
    Ba: 'BA' as ProjectTypeEnum,
    Ma: 'MA' as ProjectTypeEnum
  };
}
