/**
 * PROX API
 * PROX API Specification
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProjectStudyCourse {
  academicDegree?: ProjectStudyCourse.AcademicDegreeEnum;
  readonly id?: string;
  name?: string;
}
export namespace ProjectStudyCourse {
  export type AcademicDegreeEnum = 'BACHELOR' | 'MASTER';
  export const AcademicDegreeEnum = {
    Bachelor: 'BACHELOR' as AcademicDegreeEnum,
    Master: 'MASTER' as AcademicDegreeEnum
  };
}
