/**
 * PROX User Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetOrganizationResponse } from './getOrganizationResponse';

export interface GetOrganizationMembershipResponse {
  organization?: GetOrganizationResponse;
  type?: GetOrganizationMembershipResponse.TypeEnum;
}
export namespace GetOrganizationMembershipResponse {
  export type TypeEnum = 'OWNER' | 'MEMBER';
  export const TypeEnum = {
    Owner: 'OWNER' as TypeEnum,
    Member: 'MEMBER' as TypeEnum
  };
}
