/**
 * PROX Company Profile Service
 * This Service is part of [PROX](https://prox.innovation-hub.de/) and is used to give companies the opportunity to create a custom profile as an informative source about it and the projects it offers
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Quarter } from './quarter';
import { CompanyInformation } from './companyInformation';
import { SocialMedia } from './socialMedia';
import { Branch } from './branch';

export interface Company {
  id: string;
  creatorId?: string;
  information: CompanyInformation;
  headquarter?: Quarter;
  quarters?: Quarter[];
  branches?: Branch[];
  socialMedia?: SocialMedia[];
}
