/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfModule } from './embeddedCollectionOfModule';
import { Link } from '../common/link';

/**
 * Resources of Module
 */
export interface CollectionModelOfModule {
  _embedded: EmbeddedCollectionOfModule;
  /**
   * Link collection
   */
  _links: { [key: string]: Link };
}
