version: '3.7'

services:
  web-client:
    build:
      context: ./..
      dockerfile: docker/Dockerfile-local
    ports:
      - '4200:80'
    networks:
      - prox
networks:
  prox:
    driver: bridge
