FROM node:18-bullseye-slim as build
ENV NODE_ENV=local
ENV APP_ENV=local
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json package-lock.json tsconfig.json tailwind.config.js ./
# add app
COPY . /usr/src/app
RUN npm ci --include=dev
RUN npm install -g @angular/cli
RUN npm run build:dev

FROM nginx:1.23-alpine

COPY --from=build /usr/src/app/dist/prox-web-client /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
