/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelOfFaculty } from './entityModelOfFaculty';
import { Links } from '../common/links';

export interface CollectionModelOfEntityModelOfFaculty {
  _embedded?: Array<EntityModelOfFaculty>;
  _links?: Links;
}
