/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileImage } from './profileImage';
import { Links } from '../common/links';
import { Publication } from './publication';
import { ResearchSubject } from './researchSubject';
import { ContactInformation } from './contactInformation';

export interface EntityModelOfProfessor {
  _links?: Links;
  contactInformation?: ContactInformation;
  id?: string;
  name?: string;
  profileImage?: ProfileImage;
  publications?: Array<Publication>;
  researchSubjects?: Array<ResearchSubject>;
  vita?: string;
}
