/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelProfessorEmbedded } from './pagedModelEntityModelProfessorEmbedded';
import { Link } from './link';

export interface PagedModelEntityModelProfessor {
  _embedded?: PagedModelEntityModelProfessorEmbedded;
  _links?: { [key: string]: Link };
  page?: PageMetadata;
}
