node {
  def revision
  def changelist

  def repository = 'docker.nexus.archi-lab.io/archilab'
  def image
  def tag

  def server = 'tcp://10.10.10.42:2376'
  def certs = 'prox-dev-certs'
  def tagPrefix = '-dev'

  stage('Checkout') {
    checkout scm

    def packageJSON = readJSON file: 'package.json'

    revision = packageJSON.version
    changelist = tagPrefix + '-' + env.BUILD_NUMBER

    image = packageJSON.name
    tag = revision + changelist
  }

  stage('Build') {
    docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
      sh "docker build -t ${image} -f ./src/docker/Dockerfile ."
      sh "docker tag ${image} ${image}:${tag}"
      sh "docker push ${image}:${tag}"
    }
  }

  stage('Deploy') {
    docker.withServer(server, certs) {
      docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
        sh "env REPOSITORY=${repository} IMAGE=${image} TAG=${tag} \
                    docker stack deploy \
                    --with-registry-auth \
                    -c src/main/docker/docker-compose.yml \
                    -c src/main/docker/docker-compose.prod.yml \
                    ${image}"
      }
    }
  }
}
