/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SupervisorName1 = string;
export type Created = string;
export type CreatorName1 = string;
export type Description1 = string;
export type ShortDescription1 = string;
export type Requirement1 = string;
export type Modules = string;
export type Name1 = string;
export type Context = 'COMPANY' | 'PROFESSOR';
export type Modified = string;
export type Status = 'VERFÜGBAR' | 'LAUFEND' | 'ABGESCHLOSSEN';

export interface Project {
  supervisorName?: SupervisorName;
  created?: Created;
  creatorID?: CreatorId;
  creatorName?: CreatorName;
  description?: Description;
  shortDescription?: ShortDescription;
  requirement?: Requirement;
  modules?: Modules;
  name?: Name;
  context?: Context;
  modified?: Modified;
  id?: Id;
  status?: Status;
  [k: string]: any;
}
export interface SupervisorName {
  supervisorName?: SupervisorName1;
  [k: string]: any;
}
export interface CreatorId {
  creatorID?: CreatorId1;
  [k: string]: any;
}
export interface CreatorId1 {
  [k: string]: any;
}
export interface CreatorName {
  creatorName?: CreatorName1;
  [k: string]: any;
}
export interface Description {
  description?: Description1;
  [k: string]: any;
}
export interface ShortDescription {
  shortDescription?: ShortDescription1;
  [k: string]: any;
}
export interface Requirement {
  requirement?: Requirement1;
  [k: string]: any;
}
export interface Name {
  name?: Name1;
  [k: string]: any;
}
export interface Id {
  [k: string]: any;
}
