/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Key = string;
export type Modules = string;

export interface StudyProgram {
  name?: Name;
  id?: Id;
  key?: Key;
  modules?: Modules;
  [k: string]: any;
}
export interface Id {
  [k: string]: any;
}
