/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfTagCollection } from './embeddedCollectionOfTagCollection';
import { Link } from './link';

/**
 * Resources of TagCollection
 */
export interface CollectionModelOfTagCollection {
  _embedded: EmbeddedCollectionOfTagCollection;
  /**
   * Link collection
   */
  _links: { [key: string]: Link };
}
