/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfTag } from './embeddedCollectionOfTag';
import { Link } from '../common/link';

/**
 * Resources of Tag
 */
export interface CollectionModelOfTag {
  _embedded: EmbeddedCollectionOfTag;
  /**
   * Link collection
   */
  _links: { [key: string]: Link };
}
