/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagCollection } from './tagCollection';

/**
 * Embedded collection of TagCollection
 */
export interface EmbeddedCollectionOfTagCollection {
  /**
   * Resource collection
   */
  tagCollections: Array<TagCollection>;
}
