/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from '../common/link';
import { Tag } from './tag';

export interface EntityModelOfTagCollection {
  _links: { [key: string]: Link };
  referencedEntity?: string;
  tags?: Array<Tag>;
}
