/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfStudyProgram } from './embeddedCollectionOfStudyProgram';
import { Link } from './link';

/**
 * Resources of StudyProgram
 */
export interface CollectionModelOfStudyProgram {
  _embedded: EmbeddedCollectionOfStudyProgram;
  /**
   * Link collection
   */
  _links: { [key: string]: Link };
}
