/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedCollectionOfStudyCourse } from './embeddedCollectionOfStudyCourse';
import { Link } from '../common/link';

/**
 * Resources of StudyCourse
 */
export interface CollectionModelOfStudyCourse {
  _embedded: EmbeddedCollectionOfStudyCourse;
  /**
   * Link collection
   */
  _links: { [key: string]: Link };
}
