/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleType } from './moduleType';

/**
 * Embedded collection of ModuleType
 */
export interface EmbeddedCollectionOfModuleType {
  /**
   * Resource collection
   */
  moduleTypes: Array<ModuleType>;
}
