/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudyProgram } from './studyProgram';

/**
 * Embedded collection of StudyProgram
 */
export interface EmbeddedCollectionOfStudyProgram {
  /**
   * Resource collection
   */
  studyPrograms: Array<StudyProgram>;
}
