/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleType } from './moduleType';
import { Links } from './links';

export interface EntityModelOfProject {
  context: EntityModelOfProject.ContextEnum;
  created?: string;
  creatorID: string;
  creatorName: string;
  description?: string;
  id: string;
  links?: Links;
  modified?: string;
  modules?: ModuleType[];
  name: string;
  requirement?: string;
  shortDescription: string;
  status: EntityModelOfProject.StatusEnum;
  supervisorName?: string;
}
export namespace EntityModelOfProject {
  export type ContextEnum = 'COMPANY' | 'PROFESSOR';
  export const ContextEnum = {
    Company: 'COMPANY' as ContextEnum,
    Professor: 'PROFESSOR' as ContextEnum
  };
  export type StatusEnum = 'ABGESCHLOSSEN' | 'LAUFEND' | 'VERFÜGBAR';
  export const StatusEnum = {
    Abgeschlossen: 'ABGESCHLOSSEN' as StatusEnum,
    Laufend: 'LAUFEND' as StatusEnum,
    Verfgbar: 'VERFÜGBAR' as StatusEnum
  };
}
