/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from '../common/link';
import { Module } from './module';

export interface EntityModelOfProject {
  created?: string;
  creatorID: string;
  creatorName: string;
  description?: string;
  id?: string;
  _links: { [key: string]: Link };
  modified?: string;
  modules?: Array<Module>;
  name: string;
  requirement?: string;
  shortDescription: string;
  supervisorName: string;
}
