/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudyCourse } from './studyCourse';

export interface Module {
  id?: string;
  name?: string;
  projectType?: Module.ProjectTypeEnum;
  studyCourse?: StudyCourse;
}
export namespace Module {
  export type ProjectTypeEnum = 'BA' | 'MA' | 'PP' | 'UNDEFINED';
  export const ProjectTypeEnum = {
    Ba: 'BA' as ProjectTypeEnum,
    Ma: 'MA' as ProjectTypeEnum,
    Pp: 'PP' as ProjectTypeEnum,
    Undefined: 'UNDEFINED' as ProjectTypeEnum
  };
}
