/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleType } from './moduleType';

export interface StudyProgram {
  id?: string;
  key: string;
  modules?: Array<ModuleType>;
  name: string;
}
