/**
 * PROX Job Service
 * This Service is part of [PROX](https://prox.innovation-hub.de/)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Creator {
  userId?: string;
  variant?: Creator.VariantEnum;
}

export namespace Creator {
  export type VariantEnum = 'COMPANY' | 'PROFESSOR' | 'UNKNOWN';
  export const VariantEnum = {
    Company: 'COMPANY' as VariantEnum,
    Professor: 'PROFESSOR' as VariantEnum,
    Unknown: 'UNKNOWN' as VariantEnum
  };
}
