/**
 * PROX Job Service
 * This Service is part of [PROX](https://prox.innovation-hub.de/)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface JobOfferType {
  id?: string;
  type: JobOfferType.TypeEnum;
  description: string;
}
export namespace JobOfferType {
  export type TypeEnum = 'FULL_TIME' | 'PART_TIME' | 'INTERNSHIP' | 'MINIJOB' | 'STUDENT_WORKER' | 'RESEARCH_ASSISTANT';
  export const TypeEnum = {
    FullTime: 'FULL_TIME' as TypeEnum,
    PartTime: 'PART_TIME' as TypeEnum,
    Internship: 'INTERNSHIP' as TypeEnum,
    Minijob: 'MINIJOB' as TypeEnum,
    StudentWorker: 'STUDENT_WORKER' as TypeEnum,
    ResearchAssistant: 'RESEARCH_ASSISTANT' as TypeEnum
  };
}
