/**
 * PROX Job Service
 * This Service is part of [PROX](https://prox.innovation-hub.de/)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface JobOfferEntryLevel {
  id?: string;
  entryLevel: JobOfferEntryLevel.EntryLevelEnum;
  description: string;
}

export namespace JobOfferEntryLevel {
  export type EntryLevelEnum = 'CAREER_STARTER' | 'EXPERIENCED';
  export const EntryLevelEnum = {
    CareerStarter: 'CAREER_STARTER' as EntryLevelEnum,
    Experienced: 'EXPERIENCED' as EntryLevelEnum
  };
}
