/**
 * PROX Job Service
 * This Service is part of [PROX](https://prox.innovation-hub.de/)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Creator } from './creator';

export interface JobOffer {
  id?: string;
  title: string;
  description: string;
  availableTypes?: Set<JobOffer.AvailableTypesEnum>;
  entryLevels?: Set<JobOffer.EntryLevelsEnum>;
  earliestStartOfEmployment?: string;
  createdAt?: string;
  createdBy?: Creator;
}
export namespace JobOffer {
  export type AvailableTypesEnum =
    | 'FULL_TIME'
    | 'PART_TIME'
    | 'INTERNSHIP'
    | 'MINIJOB'
    | 'STUDENT_WORKER'
    | 'RESEARCH_ASSISTANT';
  export const AvailableTypesEnum = {
    FullTime: 'FULL_TIME' as AvailableTypesEnum,
    PartTime: 'PART_TIME' as AvailableTypesEnum,
    Internship: 'INTERNSHIP' as AvailableTypesEnum,
    Minijob: 'MINIJOB' as AvailableTypesEnum,
    StudentWorker: 'STUDENT_WORKER' as AvailableTypesEnum,
    ResearchAssistant: 'RESEARCH_ASSISTANT' as AvailableTypesEnum
  };
  export type EntryLevelsEnum = 'CAREER_STARTER' | 'EXPERIENCED';
  export const EntryLevelsEnum = {
    CareerStarter: 'CAREER_STARTER' as EntryLevelsEnum,
    Experienced: 'EXPERIENCED' as EntryLevelsEnum
  };
}
