name: CI

on:
  # Run on every pull request
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

env:
  NODE_VERSION: 16.x
  DOCKER_REGISTRY: quay.io/innovation-hub-bergisches-rheinland

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test:ci

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist.zip
          path: dist

      - name: Upload Build
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build-artifact
          retention-days: 14
          path: dist.zip
          if-no-files-found: ignore

      - name: Archive code coverage result
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: coverage.zip
          path: coverage

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports-unit-tests
          retention-days: 14
          path: coverage.zip
          if-no-files-found: ignore
